### ISSUE TITLE
Import shiboken

### ISSUE THREAD

**Issue by csaez** [caron/PyQtForSoftimage#16]
Hey Steven,
I was reading your Qt module and seems to have a bug in the [shiboken import statement](https://github.com/caron/PyQtForSoftimage/blob/master/src/Qt/__init__.py#L231). I may be wrong, but AFAIK shiboken is not part of PySide package and should be imported as `import shiboken`.

Hope this helps,
Cheers!

**Comment by caron** [comment]
check out beta6! 41bd8854d8b295783841477f50cd084d619b3202
