### ISSUE TITLE
PyQt issue with 2015

### ISSUE THREAD

**Issue by Druitre** [caron/PyQtForSoftimage#17]
Hi,

I'm having a hell of a time getting PyQt to work. I'm following all instructions - installing Python, Pywin, PyQt, (setting environment variable Path correctly!). But when I then install the addon Soft immediately returns the following error:

    # ERROR : Traceback (most recent call last):
    #   File "<Script Block 2>", line 2, in <module>
    #     import sip
    # ImportError: No module named sip
    #  - [line 2 in G:\Jaspers XSI Workgroup\Addons\PyQtForSoftimage\Application\Plugins\pyqt_example.py]
    # ERROR : Traceback (most recent call last):
    #   File "<Script Block 2>", line 1, in <module>
    #     from PyQt4.QtCore import Qt
    # ImportError: No module named PyQt4.QtCore
    #  - [line 1 in G:\Jaspers XSI Workgroup\Addons\PyQtForSoftimage\Application\Plugins\qtevents.py]

I've tried several versions of all Python stuff - from 2.6 up to 5 - checking in cmd: to see if Python is actually recognized on my system - but nothing helps so far.

Can anyone confirm if they have PyQt addon working in SI 2015 and if so, what versions of Python/Pywin/PyQt?

Thanks,
Jasper

**Comment by Druitre** [comment]
Eh, that's odd, can't enter the error message?

**Comment by Druitre** [comment]
# ERROR : Traceback (most recent call last):
#   File "<Script Block 2>", line 2, in <module>
#     import sip
# ImportError: No module named sip
#  - [line 2 in G:\Jaspers XSI Workgroup\Addons\PyQtForSoftimage\Application\Plugins\pyqt_example.py]
# ERROR : Traceback (most recent call last):
#   File "<Script Block 2>", line 1, in <module>
#     from PyQt4.QtCore import Qt
# ImportError: No module named PyQt4.QtCore
#  - [line 1 in G:\Jaspers XSI Workgroup\Addons\PyQtForSoftimage\Application\Plugins\qtevents.py]

**Comment by Druitre** [comment]
//
# ERROR : Traceback (most recent call last):
#   File "<Script Block 2>", line 2, in <module>
#     import sip
# ImportError: No module named sip
#  - [line 2 in G:\Jaspers XSI Workgroup\Addons\PyQtForSoftimage\Application\Plugins\pyqt_example.py]
# ERROR : Traceback (most recent call last):
#   File "<Script Block 2>", line 1, in <module>
#     from PyQt4.QtCore import Qt
# ImportError: No module named PyQt4.QtCore
#  - [line 1 in G:\Jaspers XSI Workgroup\Addons\PyQtForSoftimage\Application\Plugins\qtevents.py]
//

**Comment by csaez** [comment]
Hey Jasper,

It seems like `PyQt4` is not in your `PYTHONPATH`.

Are you able to import PyQt4 outside Softimage?
I think this should be the first thing to check.

Try copying this into a python file, it should run fine as long as everything is correctly installed in your system.

```python
import sys
from PyQt4 import QtGui


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    mb = QtGui.QMessageBox.information(None, "Testing PyQt4",
                                       "Everything seems to be working fine :)")
    sys.exit()
```

**Comment by caron** [comment]
Thanks for helping out @csaez !

@Druitre Please make sure PyQt4 is on the path

**Comment by Druitre** [comment]
Hi guys,

yep, when I make a .py with that code and click it, it gives that
'everything is fine' message.

In my env variables I have C:/Python27 in 'Path' variable and I have
created a variable 'PYTHONPATH' with C:/Python27 as value. Should I set a
value for PyQt as well?

**Comment by Druitre** [comment]
Weird: just tried it with SI python disabled (as if I'm on pre-2014 SI) and
now it all works! (And I *am *on SI2015)

**Comment by Druitre** [comment]
Aaaand... it's fixed! Steve Blair and then Tim Crowson came with info and
it turns out I had not set the FULL path to PyQt in pythonpath variable. I
had set it to C:/Python27 instead of C:/Python27/Lib/site-packages.
Restarted SI and it's all working now.

Cheers and thanks Steve and Cesar!
Jasper
